In [1]:
#tensor operations

import torch

ones =torch.zeros(2,2) +1
twos =torch.ones(2,2) *2
threes =(torch.ones(2,2) *7-1)/2
fours =twos **2
sqrt2s =twos **0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [5]:
powers2 =twos **torch.tensor([[1,2],[3,4]])
print(powers2)

fives =ones +fours
print(fives)

dozens =threes *fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [7]:
a = torch.tensor([[1, 2],
                  [3, 4]])

b = torch.tensor([10, 20])  # shape: (2,)
print(a + b)  # 자동으로 [10, 20]이 각 행에 broadcast됨

#이게 바로 PyTorch가 강력한 이유 중 하나죠! 복잡한 shape 간에도 자동으로 맞춰줍니다.
#간단한 연산처럼 보여도, 이걸 잘 이해하고 있으면
#📌 딥러닝 모델 만들 때 텐서 shape 오류를 줄이는 데 큰 도움이 됩니다.

tensor([[11, 22],
        [13, 24]])


In [9]:
import torch

a =torch.rand(2,3)
b =torch.rand(3,2)
print(a*b)

# RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 
# 어느 한 차원도 맞지 않아서 브로드캐스트 할 수 없는 상황

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [11]:
import torch
rand =torch.rand(2,4) #그 random이 맞다
doubled =rand *(torch.ones(1,4) *2)
print(rand)
print(doubled)

tensor([[0.1161, 0.0903, 0.7056, 0.9102],
        [0.7192, 0.9436, 0.3515, 0.3888]])
tensor([[0.2323, 0.1807, 1.4112, 1.8204],
        [1.4383, 1.8872, 0.7030, 0.7776]])


In [15]:
# task1  텐서 브로드캐스트

import torch

a =torch.ones(4,3,2)
print("a shape:", a.shape)

b1 =torch.rand(3,2)
print("b1 shape:", b1.shape)

result1 = a +1
print("result shape:", result1.shape)

#a에서 3차원 모양의(4,3,2) 토치를 만들었다
#b1에서는 2차원 모양의(3,2) 토치를 만들었고
#이를 브로드캐스트 했을 떄의 결과를 보라라

a shape: torch.Size([4, 3, 2])
b1 shape: torch.Size([3, 2])
result shape: torch.Size([4, 3, 2])


In [19]:
import torch

a =torch.rand(2,4) *2-1
print('Common functions:')
print(torch.abs(a)) #절댓값
print(torch.ceil(a)) #올림값
print(torch.floor(a)) #내림값
print(torch.clamp(a, -0.5, 0.5)) #범위지정

Common functions:
tensor([[0.4118, 0.1860, 0.4834, 0.0798],
        [0.6911, 0.9416, 0.0278, 0.8633]])
tensor([[-0., -0., -0., 1.],
        [1., -0., -0., -0.]])
tensor([[-1., -1., -1.,  0.],
        [ 0., -1., -1., -1.]])
tensor([[-0.4118, -0.1860, -0.4834,  0.0798],
        [ 0.5000, -0.5000, -0.0278, -0.5000]])


In [21]:
#삼각함수 텐서
import torch
import math

angles =torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
sines =torch.sin(angles)
inverses =torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [23]:
#비트 연산자
import torch

print('\nBitwise XOR:')
a =torch.tensor([1,5,11])
b =torch.tensor([2,7,10])
print(torch.bitwise_xor(a,b))


Bitwise XOR:
tensor([3, 2, 1])


In [29]:
#tensor Reductions
import torch

a =torch.tensor([[1.,2.],[3.,4.]])

print('\nReduction ops:')
print(torch.max(a)) #최고값
print(torch.max(a).item()) #벡터의 구성요소를 반환
print(torch.mean(a)) #평균
print(torch.std(a)) #평균 편차
print(torch.prod(a)) #벡터 연산 (내정)
print(torch.unique(torch.tensor([1,2,1,2,1,2,]))) #유일값 반환


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [15]:
import torch

v1 =torch.tensor([1.,0.,0.])
v2 =torch.tensor([0.,1.,0.])
m1 =torch.rand(2,2)
m2 =torch.tensor([[3.,0.],[0.,3.]])

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1))
print('\n무작위 생성 2x2 행렬 m1:')
print(m1)

print('\n행렬 곱 (matrix multiplication)→ m1 @ m2 와 동일한 결과')
m3 =torch.linalg.matmul(m1,m2)
print('SVD (Singular Value Decomposition): 특이값 분해')
print(m3)
print('\n')
print(torch.linalg.svd(m3))


Vectors & Matrices:
tensor([ 0.,  0., -1.])

무작위 생성 2x2 행렬 m1:
tensor([[0.8632, 0.6381],
        [0.4645, 0.7914]])

행렬 곱 (matrix multiplication)→ m1 @ m2 와 동일한 결과
SVD (Singular Value Decomposition): 특이값 분해
tensor([[2.5897, 1.9142],
        [1.3934, 2.3741]])


torch.return_types.linalg_svd(
U=tensor([[-0.7645, -0.6447],
        [-0.6447,  0.7645]]),
S=tensor([4.1529, 0.8382]),
Vh=tensor([[-0.6930, -0.7209],
        [-0.7209,  0.6930]]))


In [5]:
import torch

a=torch.ones(2,2)
b =a;

a[0][1] =561
print(b)

# 둘이 독립적이면 값 변화가 없어야 하는데 그렇지 않음 

tensor([[  1., 561.],
        [  1.,   1.]])


In [9]:
import torch

a =torch.ones(2,2)
b =a.clone()

assert b is not a
print(torch.eq(a,b))

a[0][1] =561
print(b)

# b를 a의 클론으로 선언하면 서로 공간을 분할해서 사용한다

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [15]:
# autograd 자동으로 기울기 계산을 할 것인지를 정하는 함수
import torch

a =torch.rand(2, 2, requires_grad =True)
print(a)
b =a.clone()
print(b)

c =a.detach().clone()
print(c)
print(a)

tensor([[0.2404, 0.5564],
        [0.3426, 0.4722]], requires_grad=True)
tensor([[0.2404, 0.5564],
        [0.3426, 0.4722]], grad_fn=<CloneBackward0>)
tensor([[0.2404, 0.5564],
        [0.3426, 0.4722]])
tensor([[0.2404, 0.5564],
        [0.3426, 0.4722]], requires_grad=True)


In [19]:
import torch

# cpu gpu 연산 가능 여부 확인
if torch.cuda.is_available():
    print('we have a CUDA accelerator!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [23]:
import torch
if torch.cuda.is_available():
    gpu_rand =torch.rand(2, 2, device =torch.cuda.current_device())
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [27]:
import torch
device =torch.cuda.current_device() if torch.cuda.is_available() else torch.device('cpu')
print('Device: {}'.format(device))

x =torch.rand(2, 2, device =device)
print(x)
# 셀 수행 후 device 지정해서 호출하는 모습

Device: cpu
tensor([[0.9682, 0.2638],
        [0.8738, 0.9058]])


In [32]:
import torch
device =torch.cuda.current_device() if torch.cuda.is_available() else torch.device('cpu')
print('Device: {}'.format(device))

x =torch.rand(2,2)
y =torch.rand(2, 2, device =device)
z = x+y
# 원래 y는 gpu를 할당해서 디바이스 다름 오류가 발생해야 하는데
# 현재 환경에서는 내장 그래픽이기 떄문에 only cpu처리 되는 문제 발생

Device: cpu


In [34]:
import torch

a =torch.rand(3, 226, 226)
b =a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [36]:
import torch

a =torch.rand(1, 1, 1, 1, 1)
print(a)
b =torch.squeeze(a)
print(b)

tensor([[[[[0.9562]]]]])
tensor(0.9562)


In [54]:
import torch
a =torch.rand(1, 20) #대충 랜덤값 삽입 
print(a.shape)
print(a)
print('\n')
b =a.squeeze(0)
print(b.shape)
print(b)
print('\n')

c =torch.rand(2,2)
print(c.shape)
print(c)
print('\n')
d =c.squeeze(0)
print(d.shape)
print(d)
print('\n')

torch.Size([1, 20])
tensor([[0.1652, 0.0049, 0.8813, 0.5598, 0.1275, 0.2925, 0.4314, 0.6078, 0.8669,
         0.0888, 0.6354, 0.9785, 0.2789, 0.8630, 0.0492, 0.0157, 0.5419, 0.3595,
         0.3839, 0.9703]])


torch.Size([20])
tensor([0.1652, 0.0049, 0.8813, 0.5598, 0.1275, 0.2925, 0.4314, 0.6078, 0.8669,
        0.0888, 0.6354, 0.9785, 0.2789, 0.8630, 0.0492, 0.0157, 0.5419, 0.3595,
        0.3839, 0.9703])


torch.Size([2, 2])
tensor([[0.3604, 0.8689],
        [0.1536, 0.8432]])


torch.Size([2, 2])
tensor([[0.3604, 0.8689],
        [0.1536, 0.8432]])




In [64]:
#각 3차원 텐서를 1차원 또는 다른 형태로 reshape 하는 시시
import torch
output3d =torch.rand(6, 20, 20)
print(output3d.shape, '\n')
# 3차원 텐서, 총 요소수 6*20*20=2400

input1d =output3d.reshape(6*20*20)
print(input1d.shape,'\n
# 3차원에서 1차원으로 평탄화 하는 작업, flatten
# 총 요소수는 그대로 2400, torch.size([2400])

print(torch.reshape(output3d, (6*20*20,)).shape, '\n')
# torch.reshape =직접 호출
# 2번과 같은 1차원 flatten, 다만 reshpe()함수 형태로 직접 호출한 것

others =output3d.reshape(10, 10, 24)
print(others.shape)
# 다시 1차원 텐서를 3차원 텐서로 변환, shape만 바꾼 것
# 엔리멘탈 수는 여전히 동일하기 때문에 reshape 가능

torch.Size([6, 20, 20]) 

torch.Size([2400]) 

torch.Size([2400]) 

torch.Size([10, 10, 24])


In [68]:
import torch
a =torch.rand(4,3)
print(a)

b =a.reshape(2, 2, 3)
print(b)
# 차원을 변형해도 엔리멘탈의 수는 유지되기 때문에 문제가 없음

tensor([[0.6783, 0.1770, 0.8543],
        [0.3749, 0.1270, 0.3657],
        [0.5147, 0.9510, 0.9631],
        [0.2961, 0.3283, 0.3875]])
tensor([[[0.6783, 0.1770, 0.8543],
         [0.3749, 0.1270, 0.3657]],

        [[0.5147, 0.9510, 0.9631],
         [0.2961, 0.3283, 0.3875]]])


In [80]:
# tesk3
import torch
one_dimension_tensor =torch.rand(12)
print(one_dimension_tensor)

two_dimensions_tensor =one_dimension_tensor.reshape(3,4)
print(two_dimensions_tensor)

tensor([0.8223, 0.4705, 0.6499, 0.0184, 0.6371, 0.3851, 0.7706, 0.1062, 0.6523,
        0.5119, 0.0719, 0.0301])
tensor([[0.8223, 0.4705, 0.6499, 0.0184],
        [0.6371, 0.3851, 0.7706, 0.1062],
        [0.6523, 0.5119, 0.0719, 0.0301]])


In [82]:
# task4
import torch
one_dimension_tensor =torch.rand(120)
print(one_dimension_tensor)

four_dimensions_tensor =one_dimension_tensor.reshape(1, 3, 4, 10)
print(four_dimensions_tensor)

tensor([0.9488, 0.5872, 0.9342, 0.0548, 0.7080, 0.8568, 0.6871, 0.9450, 0.3052,
        0.8218, 0.9451, 0.8008, 0.6996, 0.5286, 0.3822, 0.3425, 0.8062, 0.9877,
        0.6539, 0.1713, 0.2870, 0.6972, 0.8661, 0.4157, 0.0602, 0.3977, 0.0255,
        0.3643, 0.5295, 0.1337, 0.3315, 0.4045, 0.4187, 0.6262, 0.9859, 0.2841,
        0.6399, 0.3204, 0.6298, 0.0498, 0.5163, 0.4922, 0.9409, 0.9157, 0.0949,
        0.3593, 0.1447, 0.0626, 0.8547, 0.4962, 0.8497, 0.6018, 0.8896, 0.5371,
        0.1843, 0.4631, 0.4911, 0.9543, 0.4905, 0.8238, 0.9021, 0.9507, 0.7047,
        0.3045, 0.3246, 0.9126, 0.7942, 0.4479, 0.6893, 0.9693, 0.5878, 0.7806,
        0.3324, 0.3724, 0.9377, 0.9510, 0.3438, 0.7124, 0.7276, 0.3796, 0.3067,
        0.4611, 0.6175, 0.5735, 0.1521, 0.4199, 0.0791, 0.4747, 0.7965, 0.0144,
        0.0856, 0.0530, 0.4999, 0.9893, 0.6823, 0.0184, 0.2236, 0.1060, 0.7991,
        0.5502, 0.3544, 0.0104, 0.5069, 0.3910, 0.0882, 0.4952, 0.8230, 0.9312,
        0.0024, 0.0123, 0.9407, 0.2618, 

In [7]:
# perceptron

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

device ='cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

#data preparation
x =torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]]).to(device)
y =torch.FloatTensor([[0],[1],[1],[0]]).to(device)

#network architecture
class SingleLayerPerceptron(nn.Module):
    def _init_(self, input_size, output_size =1):
        super(SingleLayerPerceptron, self)._init_()
        self.layer =nn.Sequential(nn.Linear(input_size, output_size, bias=True), nn.Sigmoid())

    def forward(self, x):
        output =self.layer(x)
        return output

#training settings
model =SingleLayerPerceptron(2,1).to(device)
criterion =torch.nn.BCELoss().to(device)
optimizer =torch.optim.SGD(model.parameters(), lr =1)
n_epochs =10000
tot_losses =list

TypeError: SingleLayerPerceptron.__init__() takes 1 positional argument but 3 were given