In [1]:
#tensor operations

import torch

ones =torch.zeros(2,2) +1
twos =torch.ones(2,2) *2
threes =(torch.ones(2,2) *7-1)/2
fours =twos **2
sqrt2s =twos **0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [5]:
powers2 =twos **torch.tensor([[1,2],[3,4]])
print(powers2)

fives =ones +fours
print(fives)

dozens =threes *fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [7]:
a = torch.tensor([[1, 2],
                  [3, 4]])

b = torch.tensor([10, 20])  # shape: (2,)
print(a + b)  # 자동으로 [10, 20]이 각 행에 broadcast됨

#이게 바로 PyTorch가 강력한 이유 중 하나죠! 복잡한 shape 간에도 자동으로 맞춰줍니다.
#간단한 연산처럼 보여도, 이걸 잘 이해하고 있으면
#📌 딥러닝 모델 만들 때 텐서 shape 오류를 줄이는 데 큰 도움이 됩니다.

tensor([[11, 22],
        [13, 24]])


In [9]:
import torch

a =torch.rand(2,3)
b =torch.rand(3,2)
print(a*b)

# RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 
# 어느 한 차원도 맞지 않아서 브로드캐스트 할 수 없는 상황

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [11]:
import torch
rand =torch.rand(2,4) #그 random이 맞다
doubled =rand *(torch.ones(1,4) *2)
print(rand)
print(doubled)

tensor([[0.1161, 0.0903, 0.7056, 0.9102],
        [0.7192, 0.9436, 0.3515, 0.3888]])
tensor([[0.2323, 0.1807, 1.4112, 1.8204],
        [1.4383, 1.8872, 0.7030, 0.7776]])


In [15]:
# task1  텐서 브로드캐스트

import torch

a =torch.ones(4,3,2)
print("a shape:", a.shape)

b1 =torch.rand(3,2)
print("b1 shape:", b1.shape)

result1 = a +1
print("result shape:", result1.shape)

#a에서 3차원 모양의(4,3,2) 토치를 만들었다
#b1에서는 2차원 모양의(3,2) 토치를 만들었고
#이를 브로드캐스트 했을 떄의 결과를 보라라

a shape: torch.Size([4, 3, 2])
b1 shape: torch.Size([3, 2])
result shape: torch.Size([4, 3, 2])


In [19]:
import torch

a =torch.rand(2,4) *2-1
print('Common functions:')
print(torch.abs(a)) #절댓값
print(torch.ceil(a)) #올림값
print(torch.floor(a)) #내림값
print(torch.clamp(a, -0.5, 0.5)) #범위지정

Common functions:
tensor([[0.4118, 0.1860, 0.4834, 0.0798],
        [0.6911, 0.9416, 0.0278, 0.8633]])
tensor([[-0., -0., -0., 1.],
        [1., -0., -0., -0.]])
tensor([[-1., -1., -1.,  0.],
        [ 0., -1., -1., -1.]])
tensor([[-0.4118, -0.1860, -0.4834,  0.0798],
        [ 0.5000, -0.5000, -0.0278, -0.5000]])


In [21]:
#삼각함수 텐서
import torch
import math

angles =torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
sines =torch.sin(angles)
inverses =torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [23]:
#비트 연산자
import torch

print('\nBitwise XOR:')
a =torch.tensor([1,5,11])
b =torch.tensor([2,7,10])
print(torch.bitwise_xor(a,b))


Bitwise XOR:
tensor([3, 2, 1])


In [29]:
#tensor Reductions
import torch

a =torch.tensor([[1.,2.],[3.,4.]])

print('\nReduction ops:')
print(torch.max(a)) #최고값
print(torch.max(a).item()) #벡터의 구성요소를 반환
print(torch.mean(a)) #평균
print(torch.std(a)) #평균 편차
print(torch.prod(a)) #벡터 연산 (내정)
print(torch.unique(torch.tensor([1,2,1,2,1,2,]))) #유일값 반환


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [39]:
import torch

v1 =torch.tensor([1.,0.,0.])
v2 =torch.tensor([0.,1.,0.])
m1 =torch.rand(2,2)
m2 =torch.tensor([[3.,0.],[0.,3.]])

print('\n Vectors & Matrices:')
print(torch.linalg.cross(v2, v1))
print(m1)
m3 =torch.linalg.matmul(m1,m2)
print(m3)
print(torch.linalg.svd(m3))


 Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.8819, 0.6753],
        [0.8480, 0.2776]])
tensor([[2.6457, 2.0259],
        [2.5441, 0.8328]])
torch.return_types.linalg_svd(
U=tensor([[-0.7835, -0.6214],
        [-0.6214,  0.7835]]),
S=tensor([4.2167, 0.6998]),
Vh=tensor([[-0.8665, -0.4992],
        [ 0.4992, -0.8665]]))
